In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['Chinese','English','Math','Geogrophy','History'],
             index = range(1,51)
             )
scores_pd

    Chinese  English  Math  Geogrophy  History
1        55       74    74         53       52
2        64       65    90         80       95
3        72       50    77         97       92
4        72       83    96         82       64
5        98       84    59         75       66
6        89       81    83         76       92
7        99       65    85         51       64
8        66       87    94         58       73
9        84       55    70         81       88
10       65       76    99         80       94
11       91      100    55         60       81
12       74       92    65         97       52
13       76       52    58         61      100
14       72       51    90         90       94
15       87       64    57         98       56
16       53       74    60         54       63
17       78       84    78         97       63
18       85       85    50         55       55
19       65       80    89         68       74
20       72       93    96         77       84
21       80       81    91         59       97
22       95       89    71         61       98
23       65       74    56         73       64
24       84       67    93         62       61
25       78       88    86         57       70
26       59       99    97         79       97
27       78       91    57         50       87
28       76       63    78         89       55
29       97       89    60        100       82
30       97       51    93         84       77
31       84       98    95         72      100
32       62       67    87         55       52
33       91       65    56        100       74
34       85       51    74         62       72
35       84       86    98        100       50
36       68       75    54         74       84
37       84       74    75         82       97
38       83       62    52         84       52
39       67       54    58         58       86
40       85       73    59         86       77
41       93       72    68         53       92
42       88       83    57         84       51
43       54       85    82         97       97
44       91       94    62         79       83
45       71       72    86         89       86
46       66       91    91         91       75
47       96       72    68         72       87
48       98       70    85         99       52
49       87       92    79         90       70
50       83      100    55         78       87

In [2]:
scores_pd.index.name = "Number"
scores_pd.columns.name = "Subject"
scores_pd

Subject  Chinese  English  Math  Geogrophy  History
Number
1             55       74    74         53       52
2             64       65    90         80       95
3             72       50    77         97       92
4             72       83    96         82       64
5             98       84    59         75       66
6             89       81    83         76       92
7             99       65    85         51       64
8             66       87    94         58       73
9             84       55    70         81       88
10            65       76    99         80       94
11            91      100    55         60       81
12            74       92    65         97       52
13            76       52    58         61      100
14            72       51    90         90       94
15            87       64    57         98       56
16            53       74    60         54       63
17            78       84    78         97       63
18            85       85    50         55       55
19            65       80    89         68       74
20            72       93    96         77       84
21            80       81    91         59       97
22            95       89    71         61       98
23            65       74    56         73       64
24            84       67    93         62       61
25            78       88    86         57       70
26            59       99    97         79       97
27            78       91    57         50       87
28            76       63    78         89       55
29            97       89    60        100       82
30            97       51    93         84       77
31            84       98    95         72      100
32            62       67    87         55       52
33            91       65    56        100       74
34            85       51    74         62       72
35            84       86    98        100       50
36            68       75    54         74       84
37            84       74    75         82       97
38            83       62    52         84       52
39            67       54    58         58       86
40            85       73    59         86       77
41            93       72    68         53       92
42            88       83    57         84       51
43            54       85    82         97       97
44            91       94    62         79       83
45            71       72    86         89       86
46            66       91    91         91       75
47            96       72    68         72       87
48            98       70    85         99       52
49            87       92    79         90       70
50            83      100    55         78       87

In [3]:
display(scores_pd['Chinese'][:10])
scores_pd['Math'][:10]

Number
1     55
2     64
3     72
4     72
5     98
6     89
7     99
8     66
9     84
10    65
Name: Chinese, dtype: int64

Number
1     74
2     90
3     77
4     96
5     59
6     83
7     85
8     94
9     70
10    99
Name: Math, dtype: int64

In [4]:
scores_pd['Chinese'] + scores_pd['English'] + scores_pd['Geogrophy'] + scores_pd['History'] + scores_pd['Math']

Number
1     308
2     394
3     388
4     397
5     382
6     421
7     364
8     378
9     378
10    414
11    387
12    380
13    347
14    397
15    362
16    304
17    400
18    330
19    376
20    422
21    408
22    414
23    332
24    367
25    379
26    431
27    363
28    361
29    428
30    402
31    449
32    323
33    386
34    344
35    418
36    355
37    412
38    333
39    323
40    380
41    378
42    363
43    415
44    409
45    404
46    414
47    395
48    404
49    418
50    403
dtype: int64

In [5]:
scores_pd['Total'] = scores_pd[['Chinese','English','Math','Geogrophy','History']].sum(axis=1)
scores_pd
scores_pd['Average'] = scores_pd[['Chinese','English','Math','Geogrophy','History']].mean(axis=1)
scores_pd

Subject  Chinese  English  Math  Geogrophy  History  Total  Average
Number
1             55       74    74         53       52    308     61.6
2             64       65    90         80       95    394     78.8
3             72       50    77         97       92    388     77.6
4             72       83    96         82       64    397     79.4
5             98       84    59         75       66    382     76.4
6             89       81    83         76       92    421     84.2
7             99       65    85         51       64    364     72.8
8             66       87    94         58       73    378     75.6
9             84       55    70         81       88    378     75.6
10            65       76    99         80       94    414     82.8
11            91      100    55         60       81    387     77.4
12            74       92    65         97       52    380     76.0
13            76       52    58         61      100    347     69.4
14            72       51    90         90       94    397     79.4
15            87       64    57         98       56    362     72.4
16            53       74    60         54       63    304     60.8
17            78       84    78         97       63    400     80.0
18            85       85    50         55       55    330     66.0
19            65       80    89         68       74    376     75.2
20            72       93    96         77       84    422     84.4
21            80       81    91         59       97    408     81.6
22            95       89    71         61       98    414     82.8
23            65       74    56         73       64    332     66.4
24            84       67    93         62       61    367     73.4
25            78       88    86         57       70    379     75.8
26            59       99    97         79       97    431     86.2
27            78       91    57         50       87    363     72.6
28            76       63    78         89       55    361     72.2
29            97       89    60        100       82    428     85.6
30            97       51    93         84       77    402     80.4
31            84       98    95         72      100    449     89.8
32            62       67    87         55       52    323     64.6
33            91       65    56        100       74    386     77.2
34            85       51    74         62       72    344     68.8
35            84       86    98        100       50    418     83.6
36            68       75    54         74       84    355     71.0
37            84       74    75         82       97    412     82.4
38            83       62    52         84       52    333     66.6
39            67       54    58         58       86    323     64.6
40            85       73    59         86       77    380     76.0
41            93       72    68         53       92    378     75.6
42            88       83    57         84       51    363     72.6
43            54       85    82         97       97    415     83.0
44            91       94    62         79       83    409     81.8
45            71       72    86         89       86    404     80.8
46            66       91    91         91       75    414     82.8
47            96       72    68         72       87    395     79.0
48            98       70    85         99       52    404     80.8
49            87       92    79         90       70    418     83.6
50            83      100    55         78       87    403     80.6

In [6]:
scores_pd['Rank'] = scores_pd['Total'].rank(method='first',ascending=False)
scores_pd

Subject  Chinese  English  Math  Geogrophy  History  Total  Average  Rank
Number
1             55       74    74         53       52    308     61.6  49.0
2             64       65    90         80       95    394     78.8  23.0
3             72       50    77         97       92    388     77.6  24.0
4             72       83    96         82       64    397     79.4  20.0
5             98       84    59         75       66    382     76.4  27.0
6             89       81    83         76       92    421     84.2   5.0
7             99       65    85         51       64    364     72.8  36.0
8             66       87    94         58       73    378     75.6  31.0
9             84       55    70         81       88    378     75.6  32.0
10            65       76    99         80       94    414     82.8   9.0
11            91      100    55         60       81    387     77.4  25.0
12            74       92    65         97       52    380     76.0  28.0
13            76       52    58         61      100    347     69.4  42.0
14            72       51    90         90       94    397     79.4  21.0
15            87       64    57         98       56    362     72.4  39.0
16            53       74    60         54       63    304     60.8  50.0
17            78       84    78         97       63    400     80.0  19.0
18            85       85    50         55       55    330     66.0  46.0
19            65       80    89         68       74    376     75.2  34.0
20            72       93    96         77       84    422     84.4   4.0
21            80       81    91         59       97    408     81.6  14.0
22            95       89    71         61       98    414     82.8  10.0
23            65       74    56         73       64    332     66.4  45.0
24            84       67    93         62       61    367     73.4  35.0
25            78       88    86         57       70    379     75.8  30.0
26            59       99    97         79       97    431     86.2   2.0
27            78       91    57         50       87    363     72.6  37.0
28            76       63    78         89       55    361     72.2  40.0
29            97       89    60        100       82    428     85.6   3.0
30            97       51    93         84       77    402     80.4  18.0
31            84       98    95         72      100    449     89.8   1.0
32            62       67    87         55       52    323     64.6  47.0
33            91       65    56        100       74    386     77.2  26.0
34            85       51    74         62       72    344     68.8  43.0
35            84       86    98        100       50    418     83.6   6.0
36            68       75    54         74       84    355     71.0  41.0
37            84       74    75         82       97    412     82.4  12.0
38            83       62    52         84       52    333     66.6  44.0
39            67       54    58         58       86    323     64.6  48.0
40            85       73    59         86       77    380     76.0  29.0
41            93       72    68         53       92    378     75.6  33.0
42            88       83    57         84       51    363     72.6  38.0
43            54       85    82         97       97    415     83.0   8.0
44            91       94    62         79       83    409     81.8  13.0
45            71       72    86         89       86    404     80.8  15.0
46            66       91    91         91       75    414     82.8  11.0
47            96       72    68         72       87    395     79.0  22.0
48            98       70    85         99       52    404     80.8  16.0
49            87       92    79         90       70    418     83.6   7.0
50            83      100    55         78       87    403     80.6  17.0

In [7]:
scores_pd.sort_values(by='Rank')

Subject  Chinese  English  Math  Geogrophy  History  Total  Average  Rank
Number
31            84       98    95         72      100    449     89.8   1.0
26            59       99    97         79       97    431     86.2   2.0
29            97       89    60        100       82    428     85.6   3.0
20            72       93    96         77       84    422     84.4   4.0
6             89       81    83         76       92    421     84.2   5.0
35            84       86    98        100       50    418     83.6   6.0
49            87       92    79         90       70    418     83.6   7.0
43            54       85    82         97       97    415     83.0   8.0
10            65       76    99         80       94    414     82.8   9.0
22            95       89    71         61       98    414     82.8  10.0
46            66       91    91         91       75    414     82.8  11.0
37            84       74    75         82       97    412     82.4  12.0
44            91       94    62         79       83    409     81.8  13.0
21            80       81    91         59       97    408     81.6  14.0
45            71       72    86         89       86    404     80.8  15.0
48            98       70    85         99       52    404     80.8  16.0
50            83      100    55         78       87    403     80.6  17.0
30            97       51    93         84       77    402     80.4  18.0
17            78       84    78         97       63    400     80.0  19.0
4             72       83    96         82       64    397     79.4  20.0
14            72       51    90         90       94    397     79.4  21.0
47            96       72    68         72       87    395     79.0  22.0
2             64       65    90         80       95    394     78.8  23.0
3             72       50    77         97       92    388     77.6  24.0
11            91      100    55         60       81    387     77.4  25.0
33            91       65    56        100       74    386     77.2  26.0
5             98       84    59         75       66    382     76.4  27.0
12            74       92    65         97       52    380     76.0  28.0
40            85       73    59         86       77    380     76.0  29.0
25            78       88    86         57       70    379     75.8  30.0
8             66       87    94         58       73    378     75.6  31.0
9             84       55    70         81       88    378     75.6  32.0
41            93       72    68         53       92    378     75.6  33.0
19            65       80    89         68       74    376     75.2  34.0
24            84       67    93         62       61    367     73.4  35.0
7             99       65    85         51       64    364     72.8  36.0
27            78       91    57         50       87    363     72.6  37.0
42            88       83    57         84       51    363     72.6  38.0
15            87       64    57         98       56    362     72.4  39.0
28            76       63    78         89       55    361     72.2  40.0
36            68       75    54         74       84    355     71.0  41.0
13            76       52    58         61      100    347     69.4  42.0
34            85       51    74         62       72    344     68.8  43.0
38            83       62    52         84       52    333     66.6  44.0
23            65       74    56         73       64    332     66.4  45.0
18            85       85    50         55       55    330     66.0  46.0
32            62       67    87         55       52    323     64.6  47.0
39            67       54    58         58       86    323     64.6  48.0
1             55       74    74         53       52    308     61.6  49.0
16            53       74    60         54       63    304     60.8  50.0

In [8]:
def format60(v:int):
    if v >= 60:
        return 'Pass'
    else:
        return 'Not pass'
scores_pd[['Chinese','English','Math','Geogrophy','History']].style.format(format60)

In [9]:
scores_pd[['Chinese','English','Math','Geogrophy','History']].style.highlight_between(
left=0,right=59,color='blue')

In [10]:
scores_pd.style.highlight_between(left=0,
                                  right=59,
                                  color='blue',
                                  subset=['Chinese','English','Math','Geogrophy','History'])